name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                include:
                    - os: macos-latest
                      platform: mac
                    - os: ubuntu-latest
                      platform: linux
                    - os: windows-latest
                      platform: windows
                      electron_legacy: v36.0.0-nightly.20250227

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Run Electron Builder
              if: ${{ matrix.platform != 'mac' }}
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.ETOKEN }}

            - name: Run Electron Builder
              if: ${{ matrix.platform == 'mac' }}
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.ETOKEN }}

            - name: Run Electron Builder for Legacy Windows
              if: ${{ matrix.platform == 'windows' }}
              run: |
                  if (Test-Path "$env:LOCALAPPDATA\Electron\Cache") {
                      Remove-Item -Path "$env:LOCALAPPDATA\Electron\Cache" -Recurse -Force
                  }
                  pnpm electron-builder --windows --x64 --publish always --config.artifactName='${productName}-${os}7-${arch}.${ext}' --config.win.target='zip'
                  pnpm electron-builder --windows --x64 --publish always --config.artifactName='${productName}-${os}7-${arch}.${ext}' --config.win.target='nsis'
              env:
                  GH_TOKEN: ${{ secrets.ETOKEN }}
                  ELECTRON_MIRROR: "https://github.com/e3kskoy7wqk/Electron-for-windows-7/releases/download/"
                  ELECTRON_CUSTOM_DIR: ${{ matrix.electron_legacy }}
                  ELECTRON_CUSTOM_FILENAME: "dist.zip"
